package blfsparser;

public class PHPConfig {
	public static final String PHP_CONFIG = "./configure --prefix=/usr                    \\\n"
			+ "            --sysconfdir=/etc                \\\n"
			+ "            --with-apxs2                     \\\n"
			+ "            --with-config-file-path=/etc     \\\n"
			+ "            --disable-ipv6                   \\\n"
			+ "            --with-openssl                   \\\n"
			+ "            --with-kerberos                  \\\n"
			+ "            --with-pcre-regex=/usr           \\\n"
			+ "            --with-zlib                      \\\n"
			+ "            --enable-bcmath                  \\\n"
			+ "            --with-bz2                       \\\n"
			+ "            --enable-calendar                \\\n"
			+ "            --with-curl                      \\\n"
			+ "            --enable-dba=shared              \\\n"
			+ "            --with-gdbm                      \\\n"
			+ "            --enable-exif                    \\\n"
			+ "            --enable-ftp                     \\\n"
			+ "            --with-openssl-dir=/usr          \\\n"
			+ "            --with-gd=/usr                   \\\n"
			+ "            --with-jpeg-dir=/usr             \\\n"
			+ "            --with-png-dir=/usr              \\\n"
			+ "            --with-zlib-dir=/usr             \\\n"
			+ "            --with-xpm-dir=/usr/X11R6/lib    \\\n"
			+ "            --with-freetype-dir=/usr         \\\n"
			+ "            --with-t1lib                     \\\n"
			+ "            --with-gettext                   \\\n"
			+ "            --with-gmp                       \\\n"
			+ "            --with-ldap                      \\\n"
			+ "            --with-ldap-sasl                 \\\n"
			+ "            --enable-mbstring                \\\n"
			+ "            --with-mysql                     \\\n"
			+ "            --with-mysqli=mysqlnd            \\\n"
			+ "            --with-mysql-sock=/var/run/mysql \\\n"
			+ "            --with-unixODBC=/usr             \\\n"
			+ "            --with-pdo-mysql                 \\\n"
			+ "            --with-pdo-odbc=unixODBC,/usr    \\\n"
			+ "            --with-pdo-pgsql                 \\\n"
			+ "            --without-pdo-sqlite             \\\n"
			+ "            --with-pgsql                     \\\n"
			+ "            --with-pspell                    \\\n"
			+ "            --with-readline                  \\\n"
			+ "            --with-snmp                      \\\n"
			+ "            --enable-sockets                 \\\n"
			+ "            --with-tidy                      \\\n"
			+ "            --with-xsl                       \\\n"
			+ "            --enable-fpm                     \\\n"
			+ "            --with-fpm-user=apache           \\\n"
			+ "            --with-fpm-group=apache          \\\n"
			+ "            --with-fpm-systemd               \\\n"
			+ "            --with-iconv                      &&\n"
			+ "make";
}
