#!/usr/bin/python

import os
import string
import pwd
import subprocess
from subprocess import check_output
import getpass
from Crypto.Cipher import AES
import base64
import logging
#----------------------runWithEnvAs-------------------------------------
def runWithEnvAs(user, commands, env, cwd):
    userRecord = pwd.getpwnam(user)
    userUid = userRecord.pw_uid
    userGid = userRecord.pw_gid
    process = subprocess.Popen(
        commands, preexec_fn=demote(userUid, userGid), cwd=cwd, env=env
    )
    result = process.wait()
    if result != 0:
        exit()
#----------------------demote-------------------------------------------
def demote(user_uid, user_gid):
    def result():
        os.setgid(user_gid)
        os.setuid(user_uid)
    return result
#----------------------runScriptWithEnvAs-------------------------------
def runScriptWithEnvAs(user, script, env, cwd):
    runWithEnvAs(user, ['/bin/bash', script], env, cwd)
#----------------------runScript----------------------------------------
def runScript(script, cwd):
    process = subprocess.Popen(['/bin/bash', script], cwd=cwd)
    result = process.wait()
    if result != 0:
        exit()
#----------------------runScriptWithArgs--------------------------------
def runScriptWithArgs(script, cwd, args):
    lst = ['/bin/bash', script]
    lst.extend(args)
    process = subprocess.Popen(lst, cwd=cwd)
    result = process.wait()
    if result != 0:
        exit()
#----------------------makeLogEntry-------------------------------------
def makeLogEntry(message, logFile):
    with open(logFile, 'a') as f:
        f.write(message + '\n')
#----------------------BuildLfs-----------------------------------------
class BuildLfs:
    #------------------__init__-----------------------------------------
    def __init__(self):
        self.logger = logging.getLogger(__name__)
        self.logger.setLevel(logging.INFO)
        self.handler = logging.FileHandler('/sources/' + __name__ + '.log')
        self.formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        self.handler.setFormatter(self.formatter)
        self.logger.addHandler(self.handler)
        self.logger.info('Set log system')
        self.currentStageFile   = '/sources/currentstage'   # path file che memorizza lo stage
        self.propsFile          = 'build-properties'        #nome del file che memorizza le proprieta'
        self.stage              = ''                        #stage corrente
        self.passwords          = {}                        #passwords root e utente
        self.encoded_passwords  = {}                        #passwords criptate
        self.secret_key         = '13fFgYjK7iOyG564'        #chiave di cifratura
        self.cipher             = AES.new(self.secret_key, AES.MODE_ECB) #
        self.DEV_NAME           = ''
        self.ROOT_PART          = ''
        self.HOME_PART          = ''
        self.FORMAT_HOME        = 'n'
        self.SWAP_PART          = ''
        self.FORMAT_SWAP        = 'n'
        self.LOCALE             = 'it_IT.utf8'
        self.OS_NAME            = 'LFSLinux'
        self.OS_VERSION         = '2016.11'
        self.OS_CODENAME        = 'Lucio'
        self.DOMAIN_NAME        = 'localhost'
        self.KEYBOARD           = 'it'
        self.PAPER_SIZE         = 'A4'
        self.FULLNAME           = self.OS_NAME + ' ' + self.OS_CODENAME
        self.USERNAME           = string.lower(self.OS_NAME)
        self.HOST_NAME          = string.lower(self.OS_NAME + '-' + self.OS_CODENAME)
        self.CREATE_BACKUPS     = 'n'
        self.INSTALL_XSERVER    = 'n'
        self.INSTALL_DESKTOP_ENVIRONMENT    = 'n'
        self.DESKTOP_ENVIRONMENT            = 'xfce'
    #------------------main---------------------------------------------
    def main(self):
        print 'Do you want to start a new build or resume a build that was previously started ?'
        print '1. Start a fresh build'
        print '2. Resume the last build'
        print '3. Resume from a certain stage'
        response = raw_input('Enter your choice (1 ... 2): ')
        if response == '1':
            self.freshBuild(1)
        elif response == '2':
            rootPartition = raw_input('Enter the root partition where the build was in progress. Enter to exit: ')
            if rootPartition != '':
                # se /mnt/lfs/dev esiste smonta i mount point bind
                if os.path.exists('/mnt/lfs/dev'):
                    try:
                        check_output('umount -v /mnt/lfs/dev/pts', stderr=subprocess.STDOUT, shell=True)
                        check_output('umount -v /mnt/lfs/dev', stderr=subprocess.STDOUT, shell=True)
                        check_output('umount -v /mnt/lfs/sys', stderr=subprocess.STDOUT, shell=True)
                        check_output('umount -v /mnt/lfs/proc',stderr=subprocess.STDOUT,  shell=True)
                        check_output('umount -v /mnt/lfs/run', stderr=subprocess.STDOUT, shell=True)
                        print 'Package builder directories unmounted successfully'
                    except:
                        print 'Un-mounting wasnt successful. Continuing without it...'
                # se /mnt/lfs/sources/build-properties non esiste smonta, cancella tutto e rimonta /mnt/lfs
                if not os.path.exists('/mnt/lfs/sources/build-properties'):
                    runScript('./umountal.sh', None)
                    check_output('rm -rf /sources', shell=True)
                    check_output('rm -rf /mnt/lfs', shell=True)
                    check_output('mkdir -pv /mnt/lfs', shell=True)
                    check_output('mount -v ' + rootPartition + ' /mnt/lfs', shell=True)
                    check_output('ln -svf /mnt/lfs/sources /', shell=True)
                #se esiste carica lo stage memorizzato
                if os.path.exists('/sources/build-properties'):
                    self.stage = self.getCurrentStage()
                    self.freshBuild(self.stage)
                else:
                    check_output('./umountal.sh', shell=True)
                    print 'This is not the partition where build was in progress. Cannot continue. Exiting.'
                    print 'Please re-run this script with right inputs.'
        elif response == '3':
            print 'This function has not been implemented.'
            pass
    #------------------logCurrentStage----------------------------------
    def logCurrentStage(self, stageName):
        if os.path.exists(self.currentStageFile):
            with open(self.currentStageFile, 'w') as f:
                f.write(stageName)
    #------------------getCurrentStage----------------------------------
    def getCurrentStage(self):
        try:
            with open(self.currentStageFile, 'r') as f:
                line = f.readline()
            return line.strip()
        except:
            return 0
    #------------------freshBuild---------------------------------------
    def freshBuild(self, startFrom):
        startFrom = int(startFrom)
        if startFrom == 1:
            self.logCurrentStage('1')
            self.inputBuildProperties()
            startFrom = startFrom + 1
        else:
            self.getBuildProperties()
            #passwords['root'] = cipher.decrypt(base64.b64decode(getParamValue('ROOT_ENCPASSWORD')))
            #passwords['user'] = cipher.decrypt(base64.b64decode(getParamValue('USER_ENCPASSWORD')))

        if startFrom == 2:
            try:
                self.logCurrentStage('2')
                runScript('stage1.sh', None)
                startFrom = startFrom + 1
            except:
                #print 'Error occured while executing stage 1'
                self.logger.error('Error occured while executing stage 1', exc_info=True)
                exit()

        if startFrom == 3:
            self.logCurrentStage('3')
            env={}
            LFS='/mnt/lfs'
            LC_ALL='POSIX'
            LFS_TGT=check_output("echo $(uname -m)-lfs-linux-gnu", shell=True).strip('\n')
            PATH='/tools/bin:/bin:/usr/bin'
            env['LFS'] = LFS
            env['LC_ALL'] = LC_ALL
            env['PATH'] = PATH
            env['LFS_TGT']=LFS_TGT
            try:
                runScriptWithEnvAs('lfs', 'stage2.sh', env, '/home/lfs')
                startFrom = startFrom + 1
            except:
                #print 'Error occured while executing stage 2'
                self.logger.error('Error occured while executing stage 2', exc_info=True)
                exit()
        if startFrom == 4:
            self.logCurrentStage('4')
            try:
                runScript('/sources/stage3.sh', '/sources')
                startFrom = startFrom + 1
            except:
                #print 'Error occured while running stage 3'
                self.logger.error('Error occured while executing stage 3', exc_info=True)
                exit()
        if startFrom == 5:
            print 'Starting stage 5'
            self.logCurrentStage('5')
            try:
                runScript('/sources/stage6.sh', '/sources')
                startFrom = startFrom + 1
            except:
                #print 'Error occured while running stage 4'
                self.logger.error('Error occured while executing stage 4', exc_info=True)
                exit()
            try:
                pr = subprocess.Popen(['./enteral.sh /sources/final-stage.sh "' + self.passwords['root'] + '" "' + self.passwords['user'] + '"'], shell=True)
                pr.wait()
            except Exception as ex:
                print ex
            #if self.getParamValue('CREATE_BACKUPS') == 'y' or self.getParamValue('CREATE_BACKUPS') == 'Y':
            if string.lower(self.getParamValue('CREATE_BACKUPS')) == 'y':
                try:
                    files = os.listdir('/mnt/lfs/sources')
                    found = False
                    for file in files:
                        if file.startswith('aryalinux') and 'base-system' in file and file.endswith('.tar.xz'):
                            found = True
                            break
                    if not found:
                        p = subprocess.Popen(['./strip-debug.sh'], shell=True)
                        p.wait()
                        p = subprocess.Popen(['./backup.sh base-system y'], shell=True)
                        p.wait()
                    else:
                        print 'Base system backup already present. Not creating again'
                except:
                    #print 'Error occured while backing up base-system. Aborting.'
                    self.logger.error('Error occured while backing up base-system. Aborting.', exc_info=True)
                    exit()

        if startFrom == 6:
            #if getParamValue('INSTALL_XSERVER') == 'y' or getParamValue('INSTALL_XSERVER') == 'Y':
            if string.lower(self.getParamValue('INSTALL_XSERVER')) == 'y':
                try:
                    self.logCurrentStage('6')
                    runScriptWithArgs('/sources/enteral.sh', '/sources', ['/sources/apps/essentials.sh', self.getParamValue('USERNAME')])
                    runScriptWithArgs('/sources/enteral.sh', '/sources', ['/sources/apps/app.sh', self.getParamValue('USERNAME'), 'xserver-meta'])
                    startFrom = startFrom + 1
                    #if getParamValue('CREATE_BACKUPS') == 'y' or getParamValue('CREATE_BACKUPS') == 'Y':
                    if string.lower(self.getParamValue('CREATE_BACKUPS')) == 'y':
                        try:
                            files = os.listdir('/mnt/lfs/sources/')
                            found = False
                            for file in files:
                                if file.startswith('aryalinux') and 'base-system-with-xserver' in file and file.endswith('.tar.xz'):
                                    found = True
                                    break
                            if not found:
                                p = subprocess.Popen(['./strip-debug.sh'], shell=True)
                                p.wait()
                                p = subprocess.Popen(['./backup.sh base-system-with-xserver n'], shell=True)
                                p.wait()
                            else:
                                print 'X-Server backup already present. Not backing up again.'
                        except:
                            #print 'Error occured while backing up base-system-with-xserver. Aborting.'
                            self.logger.error('Error occured while backing up base-system-with-xserver. Aborting.', exc_info=True)
                            exit()
                except:
                    #print 'Error occured in the installation of x-server'
                    self.logger.error('Error occured in the installation of x-server', exc_info=True)
                    exit()

        if startFrom == 7:
            #if getParamValue('INSTALL_DESKTOP_ENVIRONMENT') == 'y' or getParamValue('INSTALL_DESKTOP_ENVIRONMENT') == 'Y':
            if string.lower(self.getParamValue('INSTALL_DESKTOP_ENVIRONMENT')) == 'y':
                try:
                    self.logCurrentStage('7')
                    if self.getParamValue('DESKTOP_ENVIRONMENT') == 'mate':
                        desktopEnv = 'mate'
                        runScriptWithArgs('/sources/enteral.sh', '/sources', ['/sources/apps/app.sh', self.getParamValue('USERNAME'), 'mate-desktop-environment'])
                    elif self.getParamValue('DESKTOP_ENVIRONMENT') == 'xfce':
                        desktopEnv = 'xfce'
                        runScriptWithArgs('/sources/enteral.sh', '/sources', ['/sources/apps/app.sh', self.getParamValue('USERNAME'), 'xfce-desktop-environment'])
                    startFrom = startFrom + 1
                    #if getParamValue('CREATE_BACKUPS') == 'y' or getParamValue('CREATE_BACKUPS') == 'Y':
                    if string.lower(self.getParamValue('CREATE_BACKUPS')) == 'y':
                        try:
                            files = os.listdir('/mnt/lfs/sources/')
                            found = False
                            for file in files:
                                if file.startswith('aryalinux') and 'base-system-with-' + desktopEnv in file and file.endswith('.tar.gz'):
                                    found = True
                                    break
                            if not found:
                                p = subprocess.Popen(['./strip-debug.sh'], shell=True)
                                p.wait()
                                p = subprocess.Popen(['./backup.sh base-system-with-' + desktopEnv + ' n'], shell=True)
                                p.wait()
                            else:
                                print 'Desktop environment backup already present. Not backing up again.'
                        except:
                            #print 'Error occured while backing up base-system-with-' + desktopEnv + '. Aborting.'
                            self.logger.error('Error occured while backing up base-system-with-' + desktopEnv + '. Aborting.', exc_info=True)
                            exit()
                except:
                    #print 'Error occured in the installation of desktop environment'
                    self.logger.error('Error occured in the installation of desktop environment', exc_info=True)
                    exit()
        pr = subprocess.Popen(['./createlivedisk.sh'], shell=True)
        pr.wait()
    #------------------getPassword--------------------------------------
    def getPassword(self, prompt, promptagain):
        password1 = getpass.getpass(prompt)
        password2 = getpass.getpass(promptagain)
        if password1 == password2:
            return password1.rjust(32)
        else:
            print 'Passwords do not match. Retrying...'
            return self.getPassword(prompt, promptagain)
    #------------------getParamValue------------------------------------
    def getParamValue(self, paramName):
        with open(self.propsFile) as f:
            for line in f:
                if line.startswith(paramName):
                    return line.replace(paramName, '').replace('"', '').replace('=', '', 1).strip()
        return None
    #------------------getBuildProperties-------------------------------
    def getBuildProperties(self):
        self.DEV_NAME           = self.getParamValue('DEV_NAME')
        self._ROOT_PART         = self.getParamValue('ROOT_PART')
        self.HOME_PART          = self.getParamValue('HOME_PART')
        self.FORMAT_HOME        = self.getParamValue('FORMAT_HOME')
        self.SWAP_PART          = self.getParamValue('SWAP_PART')
        self.FORMAT_SWAP        = self.getParamValue('FORMAT_SWAP')
        self.LOCALE             = self.getParamValue('LOCALE')
        self.OS_NAME            = self.getParamValue('OS_NAME')
        self.OS_VERSION         = self.getParamValue('OS_VERSION')
        self.OS_CODENAME        = self.getParamValue('OS_CODENAME')
        self.DOMAIN_NAME        = self.getParamValue('DOMAIN_NAME')
        self.KEYBOARD           = self.getParamValue('KEYBOARD')
        self.PAPER_SIZE         = self.getParamValue('PAPER_SIZE')
        self.FULLNAME           = self.getParamValue('FULLNAME')
        self.USERNAME           = self.getParamValue('USERNAME')
        self.HOST_NAME          = self.getParamValue('HOST_NAME')
        self.CREATE_BACKUPS     = self.getParamValue('CREATE_BACKUPS')
        self.INSTALL_XSERVER    = self.getParamValue('INSTALL_XSERVER')
        self.INSTALL_DESKTOP_ENVIRONMENT    = self.getParamValue('INSTALL_DESKTOP_ENVIRONMENT')
        self.DESKTOP_ENVIRONMENT            = self.getParamValue('DESKTOP_ENVIRONMENT')
        self.passwords['root'] = self.cipher.decrypt(base64.b64decode(self.getParamValue('ROOT_ENCPASSWORD')))
        self.passwords['user'] = self.cipher.decrypt(base64.b64decode(self.getParamValue('USER_ENCPASSWORD')))
    #------------------readInput----------------------------------------
    def readInput(self, message, varName, defaultValue, append=True, interactive=True):
        if append:
            with open(self.propsFile, 'a') as f:
                if interactive:
                    response = string.lower(raw_input(message))
                    if response == '':
                        response = defaultValue
                else:
                    response = defaultValue
                f.write(varName + '="' + response + '"\n')
        else:
            with open(self.propsFile, 'w') as f:
                if interactive:
                    response = string.lower(raw_input(message))
                    if response == '':
                        response = defaultValue
                else:
                    response = defaultValue
                f.write(varName + '="' + response + '"\n')
        defaultValue = response
    #------------------inputBuildProperties-----------------------------
    def inputBuildProperties(self):
        self.readInput("Bootloader Device: ", 'DEV_NAME', self.DEV_NAME, False)
        self.readInput("Root Partition: ", 'ROOT_PART', self.ROOT_PART)
        self.readInput("Home Partition: ", 'HOME_PART', self.HOME_PART)
        if self.getParamValue('HOME_PART') != '':
        #if self.HOME_PART != '':
            self.readInput('Format Home Partition? (y/N): ', 'FORMAT_HOME', self.FORMAT_HOME)
        self.readInput("Swap Partition: ", 'SWAP_PART', self.SWAP_PART)
        if self.getParamValue('SWAP_PART') != '':
        #if self.SWAP_PART != '':
            self.readInput('Format swap partition? (y/N): ', 'FORMAT_SWAP', self.FORMAT_SWAP)
        self.readInput("Locale: (e.g. it_IT.utf8) ", 'LOCALE', self.LOCALE)
        self.readInput("OS Name: ", 'OS_NAME', self.OS_NAME)
        self.readInput("OS Version: ", 'OS_VERSION', self.OS_VERSION)
        self.readInput("OS Codename: ", 'OS_CODENAME', self.OS_CODENAME)
        self.readInput("Domain Name: ", 'DOMAIN_NAME', self.DOMAIN_NAME)
        self.readInput("Keyboard Layout: (e.g. us, fr) ", 'KEYBOARD', self.KEYBOARD)
        self.readInput("Printer Paper Size: (A4/letter) ", 'PAPER_SIZE', self.PAPER_SIZE)
        self.readInput('Enter full name: ', 'FULLNAME', self.FULLNAME)
        self.readInput('Username: ', 'USERNAME', self.USERNAME)
        self.readInput('Computer Name: ', 'HOST_NAME', self.HOST_NAME)
        self.readInput('Create backups? (y/N) ', 'CREATE_BACKUPS', self.CREATE_BACKUPS)
        self.readInput("Install X Server? (y/N) ", 'INSTALL_XSERVER', self.INSTALL_XSERVER)
        #if getParamValue('INSTALL_XSERVER') == 'y' or getParamValue('INSTALL_XSERVER') == 'Y':
        if string.lower(self.getParamValue('INSTALL_XSERVER')) == 'y':
        #if string.lower(self.INSTALL_XSERVER) == 'y':
            self.readInput("Install Desktop Environment? (y/N) ", 'INSTALL_DESKTOP_ENVIRONMENT', self.INSTALL_DESKTOP_ENVIRONMENT)
            #if getParamValue('INSTALL_DESKTOP_ENVIRONMENT') == 'y' or getParamValue('INSTALL_DESKTOP_ENVIRONMENT') == 'Y':
            if string.lower(self.getParamValue('INSTALL_DESKTOP_ENVIROMENT')) == 'y':
            #if lower(self.INSTALL_DESKTOP_ENVIRONMENT) == 'y':
                self.readInput("Choose the Desktop Environment you want to install:\n xfce\n mate\n kde\n gnome\n lxde\n\nEnter your choice (xfce): ", 'DESKTOP_ENVIRONMENT', self.DESKTOP_ENVIRONMENT)
        self.passwords['root'] = self.getPassword('Enter the root password : ', 'Re-enter the root password : ')
        self.encoded_passwords['root'] = base64.b64encode(self.cipher.encrypt(self.passwords['root']))
        self.passwords['user'] = self.getPassword('Enter the user password : ', 'Re-enter the user password : ')
        self.encoded_passwords['user'] = base64.b64encode(self.cipher.encrypt(self.passwords['user']))
        self.readInput('', 'ROOT_ENCPASSWORD', self.encoded_passwords['root'], True, False)
        self.readInput('', 'USER_ENCPASSWORD', self.encoded_passwords['user'], True, False)
########################################################################
if __name__ == '__main__':
    BuildLfs().main()
