#!/bin/bash

set -e
set +h

clear

if [ $UID != "0" ]
then
	echo "Please execute as root"
	exit
fi

echo "AryaLinux 2016.04 Dawn of Justice"
echo ""

read -p "Enter the destination device (eg /dev/sda) : " DEVICE
read -p "Enter the partition to be used as root (eg /dev/sda4) : " ROOT_PART
read -p "Enter the partition to be used as swap (eg /dev/sda5) : " SWAP_PART
read -p "Enter the partition to be used as home (eg /dev/sda6) : " HOME_PART

read -p "Enter your full name : " FULL_NAME
read -p "Enter username : " USERNAME
read -p "Give a name to this system : " SYSTEM_NAME
read -p "Enter your locale (eg en_IN.utf8) : " LOCALE

clear

TIMEZONE=`tzselect`

clear

echo "AryaLinux 2016.04 Dawn of Justice"
echo ""

echo "Please review the information that you have provided below :"

echo "Install AryaLinux onto : $DEVICE"
echo "Root Partition : $ROOT_PART"
echo "Swap Partition : $SWAP_PART"
echo "Home Partition : $HOME_PART"
echo "Full name : $FULL_NAME"
echo "Username : $USERNAME"
echo "System Name : $SYSTEM_NAME"
echo "Timezone : $TIMEZONE"
echo "Locale : $LOCALE"

echo "I am about to format the partitions you have mentioned above to install AryaLinux. Are you sure you want to continue?"
read -p "Please respond (yes/no) : " RESPONSE

export TARGET="/target"
export SOURCE="/source"

if [ "x$RESPONSE" == "xyes" ]; then

	echo "Creating target..."
	mkdir -pv $TARGET

	echo "Formatting partitions..."

	mkfs.ext4 $ROOT_PART
	mount $ROOT_PART $TARGET

	if [ "x$SWAP_PART" != "x" ]; then
		mkswap $SWAP_PART
		swapon $SWAP_PART
	fi
	if [ "x$HOME_PART" != "x" ]; then
		mkfs.ext4 $HOME_PART
		mkdir -pv $TARGET/home
		mount $HOME_PART $TARGET/home
	fi

	echo "Looking for the Squashfs filesystem..."
	SFILE=`find /mnt -name root.sfs`

	if [ "x$SFILE" == "x" ]
	then
		echo "root.sfs not found. Aborting..."
		exit
	else
		mkdir -pv $SOURCE
		mount -o ro,loop $SFILE $SOURCE
		read -p "About to copy files. This would take a while. Press enter to continue..." RESPONSE
		if [ "x$RESPONSE" == "x" ]
		then
			cp -rvp $SOURCE/* $TARGET/
			clear
			echo "Done with copying. Now would chroot into the system to create your username and install the bootloader"
			echo ""
			read -p "Press enter to continue " RESPONSE
			if [ "x$RESPONSE" == "x" ]
			then

if [ -d /sys/firmware/efi ]
then

EFIPART="$DEVICE`partx -s $DEVICE | tr -s ' ' | grep "EFI" | sed "s@^ *@@g" | cut "-d " -f1`"
mkdir -pv /boot/efi

{
set +e
mount -vt vfat $EFIPART /boot/efi
set -e
}

cat > /etc/fstab << EOF
# Begin /etc/fstab

# file system  mount-point  type     options             dump  fsck
#                                                              order

$ROOT_PART     /            ext4    defaults            1     1
EOF

if [ "x$SWAP_PART" != "x" ]; then
cat >> /etc/fstab << EOF
$SWAP_PART     swap         swap     pri=1               0     0
EOF
fi

if [ "x$HOME_PART" != "x" ]; then
cat >> /etc/fstab << EOF
$HOME_PART     /home        ext4    defaults            1     1
EOF
fi

cat >> /etc/fstab <<EOF
# End /etc/fstab
EOF

cat >> /etc/fstab <<EOF
$EFIPART       /boot/efi    vfat     defaults            0     1
efivarfs       /sys/firmware/efi/efivars  efivarfs  defaults  0      1
EOF

else

cat > /etc/fstab << EOF
# Begin /etc/fstab

# file system  mount-point  type     options             dump  fsck
#                                                              order

$ROOT_PART     /            ext4    defaults            1     1
EOF

if [ "x$SWAP_PART" != "x" ]; then
cat >> /etc/fstab << EOF
$SWAP_PART     swap         swap     pri=1               0     0
EOF
fi

if [ "x$HOME_PART" != "x" ]; then
cat >> /etc/fstab << EOF
$HOME_PART     /home        ext4    defaults            1     1
EOF
fi

cat >> /etc/fstab <<EOF
# End /etc/fstab
EOF

fi


cat > nextstep.sh <<ENDOFFILE
#!/bin/bash

set -e

export FULL_NAME="$FULL_NAME"
export USERNAME="$USERNAME"
export SYSTEM_NAME="$SYSTEM_NAME"
export TIMEZONE="$TIMEZONE"
export DEV_NAME="$DEVICE"
export ROOT_PART="$ROOT_PART"
export SWAP_PART="$SWAP_PART"
export HOME_PART="$HOME_PART"
export LOCALE="$LOCALE"

systemd-machine-id-setup

clear
echo "Setting password for root :"
passwd root

clear
echo "Creating user for you..."
useradd -m -k /etc/skel -c "$FULL_NAME" $USERNAME
usermod -a -G lp $USERNAME
usermod -a -G audio $USERNAME
usermod -a -G scanner $USERNAME
usermod -a -G wheel $USERNAME
echo "Setting password for $USERNAME"
passwd $USERNAME

{
set +e
su - $USERNAME -c xdg-user-dirs-update
xdg-user-dirs-update
set -e
}

userdel -r aryalinux

if [ -d /sys/firmware/efi ]
then

	grub-install --target=x86_64-efi --efi-directory=/boot/efi  \
	   --bootloader-id="AryaLinux 2016.04 Dawn Of Justice" --recheck --debug
else
	grub-install $DEVICE
fi

ln -sfv /usr/share/zoneinfo/$TIMEZONE /etc/localtime

grub-mkconfig -o /boot/grub/grub.cfg

cat > /etc/locale.conf << EOF
LANG=$LOCALE
EOF

ENDOFFILE

chmod a+x nextstep.sh
cp -v nextstep.sh $TARGET/

export LFS="$TARGET"

mount -v --bind /dev $LFS/dev

mount -vt devpts devpts $LFS/dev/pts -o gid=5,mode=620
mount -vt proc proc $LFS/proc
mount -vt sysfs sysfs $LFS/sys
mount -vt tmpfs tmpfs $LFS/run

chroot "$LFS" /usr/bin/env -i              \
    HOME=/root TERM="$TERM" PS1='\u:\w\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin     \
    /bin/bash /nextstep.sh

rm -f nextstep.sh

rm -f $TARGET/nextstep.sh
rm -rf $TARGET/root/sources
rm -rf $TARGET/root/scripts
rm -rf $TARGET/sources
rm -rf $TARGET/tools
rm -f $TARGET/nextstep.sh

				echo "I'm done. Please reboot to log into AryaLinux.."
			fi
		fi
	fi
fi
