#!/bin/bash

set -e
set +h

export LFS=/mnt/lfs

if [ "x$ROOT_PART" == "x" ]
then

echo "Aborting because no valid root partition specified."
exit

else

mkfs -v -t ext4 $ROOT_PART
mkdir -pv $LFS
mount -v -t ext4 $ROOT_PART $LFS

fi

if [ "x$SWAP_PART" != "x" ]
then

read -p "Do you want to format swap? (y/n) " RESP

if [ "$RESP" == "y" ] || [ "$RESP" == "Y" ]
then

mkswap $SWAP_PART

fi

read -p "Do you want to turn the swap on? (y/n) " RESP

if [ "$RESP" == "y" ] || [ "$RESP" == "Y" ]
then

swapon $SWAP_PART

fi

fi

if [ "x$HOME_PART" != "x" ]
then

read -p "Do you want to format the home partition? (y/n) " RESP

if [ "$RESP" == "y" ] || [ "$RESP" == "Y" ]
then

mkdir -v $LFS/home
mkfs -v -t ext4 $HOME_PART $LFS/home

fi

read -p "Do you want to mount the home partition? (y/n) " RESP

if [ "$RESP" == "y" ] || [ "$RESP" == "Y" ]
then

mkdir -pv $LFS/home
mount -v -t ext4 $HOME_PART $LFS/home

fi

fi

tar -xf ~/sources.tar.gz -C $LFS/
chmod -v a+wt $LFS/sources

tar -xf ~/toolchain.tar.gz -C $LFS

rm -rf /tools
ln -sv $LFS/tools /

[_KERNFS_]

clear
echo "Change to the /sources directory and execute 2.sh"

cp *.sh $LFS/sources
cp install-inputs $LFS/sources
cp -rf chapter06 $LFS/sources
cp -rf postlfs $LFS/sources

[_CHROOT_]